/**
 * Created by hautruong on 9/15/17.
 */
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const VOZ_FETCH_FORUM_SUCCESS = 'VOZ_FETCH_FORUM_SUCCESS';
export const VOZ_FETCH_FORUM_ERROR = 'VOZ_FETCH_FORUM_ERROR';

export const VOZ_FETCH_THREAD_LIST_SUCCESS = 'VOZ_FETCH_THREAD_LIST_SUCCESS';
export const VOZ_FETCH_THREAD_LIST_ERROR = 'VOZ_FETCH_THREAD_LIST_ERROR';

export const VOZ_FETCH_POST_SUCCESS = 'VOZ_FETCH_POST_SUCCESS';
export const VOZ_FETCH_POST_ERROR = 'VOZ_FETCH_POST_ERROR';